config/routes.rb
Rails.application.routes.draw do
  get 'rooms/posts',   to: 'rooms#posts'
  get 'rooms/search',  to: 'rooms#search'
  

  devise_scope :user do
    get 'users/profile',  to: 'users/registrations#profile'
    post 'users/profile', to: 'users/registrations#editprofile'
    get 'users/account',  to: 'users/registrations#account'
  end
  resources :rooms
  resources :reservations

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: "home#index"
end

app/models/room.rb
class Room < ApplicationRecord
	belongs_to :user
	has_many :reservations, dependent: :destroy
	
	validates :name, presence: true
	validates :price, numericality: {only_integer: true}
	validates :place, presence: true
	validates :image_name, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
  end

  def new
    @room = Room.new
  end

  def create
    upload_file_name = nil
    
    if params[:room][:room_image]
      upload_file = params[:room][:room_image]
      extension = File.extname(upload_file)
      upload_file_name = random_string(20)
      upload_file_path = "app/assets/images/room_images/#{upload_file_name + extension}"
      File.binwrite(upload_file_path, upload_file.read)
    end

    new_params = params.require(:room).permit(:name, :intro, :price, :place).merge({image_name: upload_file_name, user_id: current_user.id})
    @room = Room.new(new_params)
    
    if @room.save
      redirect_to room_path(@room.id)
    else
      if upload_file_path.present? 
        File.delete(upload_file_path)
      end
      render "rooms/new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
    @owner = User.find(@room.user_id)
  end

  def posts
    @rooms = Room.where(user_id: current_user.id)
  end

  def search
    @rooms = Room.where("name LIKE ?", "%#{params[:keyword]}%").where("place LIKE ?", "%#{params[:place]}%")
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/new.html.erb
<div class="form-area">
  
  <h3>ルーム情報登録</h3>
  <%= render "shared/error", obj: @room %>
  <div class="separated-field"></div>
  <%= form_with model: @room, data:{turbo: false} do |f| %>
    <div class="separated-field">
      <%= f.label :name, "ルーム名", class: "form-label" %>
      <%= f.text_field :name, autofocus: true, autocomplete: "ルーム名を入力" %>
    </div>
    <div class="separated-field">
      <%= f.label :intro, "ルーム紹介", class: "form-label" %>
      <%= f.text_area :intro, rows: "5", autocomplete: "ルーム説明を入力" %>
    </div>
    <div class="separated-field">
      <%= f.label :price, "料金", class: "form-label" %>
      <%= f.number_field :price, autocomplete: "一日あたりの料金を入力" %>
    </div>
    <div class="separated-field">
      <%= f.label :place, "住所", class: "form-label" %>
      <%= f.text_field :place, autocomplete: "住所を入力" %>
    </div>
    <div class="separated-field">
      <%= f.label :room_image, "ルーム画像", class: "form-label" %>
      <%= f.file_field :room_image, accept: "image/jpg,image/jpeg,image/png,image/gif" %>
    </div>
    <div class="actions">
      <%= f.submit "登録", class: "btn-primary" %>
    </div>
  <%end%>
</div>

app/views/rooms/posts.html.erb
<div class="container">
  <h1>予約済みルーム一覧</h1>
  <table>
    <thead>
      <tr>
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>登録日</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
      <tr>
        <td><%= image_tag "room_images/#{room.image_name}", class: "reservation-index-image", alt: "部屋画像" %>
        </td>
        <td><%= link_to room.name, room_path(room.id) %></td>
        <td><%= room.intro %></td>
        <td>
          ¥<%= room.price %>
        </td>
        <td><%= room.created_at.to_date %></td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<div class="container">
  <h2>検索結果：<%= @rooms.count %>件</h2>
  <div class="search-panels">
    <% @rooms.each do |room| %>
      <div class="search-panel">
        <%= link_to room_path(room.id) do %>
          <%= image_tag "room_images/#{room.image_name}" %>
          <div class="search-profile">
            <h3><%= room.name %></h3>
            <p><%= room.place %></p>
            <p>¥<%= room.price %></p>
          </div>
        <%end%>
      </div>
    <%end%>
  </div>

</div>

app/views/rooms/show.html.erb
<div class="container room-show-container">

  <div class="room-show">
    <%= image_tag "room_images/#{@room.image_name}", class: "room-image", alt: "部屋画像"%>
    <div class="room-show-detail">
      <%= image_tag "user_images/#{@owner.profile.icon_name}", class: "owner-icon"%>
      <div class="room-show-profile">
        <h2><%= @room.name %></h2>
        <p> <%= @room.place%> </p>
      </div>
    </div>
    <div class="room-show-intro">
      <%=@room.intro%>
    </div>
  </div>

  <div class="reservation-form">
    <%= render "shared/error", obj: @reservation %>
    <%= form_with model: @reservation, url: new_reservation_path, method: :get, data:{turbo: false} do |f| %>
      <h5>¥ <%= @room.price %> /日 </h5>
      <div>
        <%= f.label :start_day, "開始日", class: "reservation-label" %>
        <%= f.date_field :start_day, autofocus: true, class:"form-control" %>
      </div>
      <div>
        <%= f.label :end_day, "終了日", class: "reservation-label" %>
        <%= f.date_field :end_day, class:"form-control" %>
      </div>
      <div>
        <%= f.label :people_count, "人数", class: "reservation-label" %>
        <%= f.number_field :people_count, class:"form-control"%>
      </div>
      <%= f.hidden_field :room_id, value: @room.id %>
      <div>
        <%= f.submit "予約する", class:"btn-primary wide-btn"%>
      </div>
    <%end%>
  </div>
</div>